# Custom supervisor configuration to run Node.js backend
[program:nodejs_backend]
command=node server.js
directory=/app/nodejs_backend
autostart=true
autorestart=true
environment=NODE_ENV="production"
stderr_logfile=/var/log/supervisor/nodejs_backend.err.log
stdout_logfile=/var/log/supervisor/nodejs_backend.out.log
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
